// Mocks generated by Mockito 5.3.0 from annotations
// in hearthstoneapp/test/unit_tests/list_of_cards_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:hearthstoneapp/src/data/datasource/local/DAOs/firestore_database.dart'
    as _i5;
import 'package:hearthstoneapp/src/data/model/hearthstone_card.dart' as _i4;
import 'package:hearthstoneapp/src/data/repository/card_list_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [CardListRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCardListRepository extends _i1.Mock
    implements _i2.CardListRepository {
  MockCardListRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.HearthstoneCard>> getData(
          {Map<String, String>? endpoint, String? keyword}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #getData, [], {#endpoint: endpoint, #keyword: keyword}),
              returnValue: _i3.Future<List<_i4.HearthstoneCard>>.value(
                  <_i4.HearthstoneCard>[]))
          as _i3.Future<List<_i4.HearthstoneCard>>);
}

/// A class which mocks [FirestoreDatabase].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirestoreDatabase extends _i1.Mock implements _i5.FirestoreDatabase {
  MockFirestoreDatabase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> storeData(List<Map<String, dynamic>>? listOfCards) =>
      (super.noSuchMethod(Invocation.method(#storeData, [listOfCards]),
              returnValue: _i3.Future<void>.value(),
              returnValueForMissingStub: _i3.Future<void>.value())
          as _i3.Future<void>);
  @override
  _i3.Future<List<Map<String, dynamic>>> getData(
          {Map<String, String>? endpoint, String? keyword}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #getData, [], {#endpoint: endpoint, #keyword: keyword}),
              returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
                  <Map<String, dynamic>>[]))
          as _i3.Future<List<Map<String, dynamic>>>);
}
